### ISSUE TITLE
Impulse Tracker hangs at startup

### ISSUE THREAD

**Issue by vruppert** [fysnet/i440fx#4]
Please have a look at this Bochs issue: [https://github.com/bochs-emu/Bochs/issues/248](url). This issue seems to be caused by the SB16 emulation, but I tried several setups to see if there are any differences. Then I noticed that the program hangs at startup with your BIOS. With the Bochs BIOS and SeaBIOS there is no hang. With the Bochs debugger I found out that there seems to be an infinite loop around e000:4006. An image for testing is provided there.

**Comment by fysnet** [comment]
I mark the memory range of 0xE0000 -> 0xEFFFF as read only in pci.asm
https://github.com/fysnet/i440fx/blob/99aa11a9c334f2a9d0349ee2728a5f61ec56f164/pci.asm#L1306-L1316
Commenting out this code makes the test image work.

However, the reason it doesn't work is that the test image (whether it be DOS, HimemX, or Jemm386) uses paging and remaps the area of 0xE0000->0xE3FFF to above the 1Meg mark.

Place a LB at 0x50999 (`lb 0x50999`), continue, and then dump the Page Table.

![pagetable](https://github.com/user-attachments/assets/c7194e18-ee5d-4103-90f9-8931eabd0c50)

If you then place a LB at 0x100BD9, this is where the `int 13h` instruction is. However, the Jemm386 driver has a 'catch' here to catch the interrupt. It then moves through a few items, *including calling some VGA code*, and then finally jumps to 0xE039A for the BIOS interrupt handler. However, paging is still enabled, so it actually jumps to a physical address above the 1Meg mark instead of physical address 0xE039A. (I am not versed in how this works, so maybe this is correct code, but it just seems off)

I don't know much about that Jemm386 extender (and am unwilling to test it), but if another extender was used, I would bet that it works as expected.

If you comment out the lines above, the page table is shown as:

![pagetable1](https://github.com/user-attachments/assets/119f5a5b-2126-4218-a848-27d6b46d13d3)

Notice the addresses from 0xDC000 to 0xFEFFFF are now mapped to their physical address. (Note: If you use the original BIOS you will get the same page table as shown here)

If I set the address at 0xE0000->0xE3FFF as R/W but leave the others as R/O, Jemm386 Page Faults:

![pf](https://github.com/user-attachments/assets/88eb0161-d180-4e3f-984b-ebec1920f816)

I think this is an error with Jemm386, not the BIOS. However, to get around this we could simply comment out the above code and forget it...

Just my opinion though.

**Comment by vruppert** [comment]
I can confirm that Impulse Tracker works when I replace the memory managers with the original DOS ones. If you think it's a bug in Jemm386, you can close this issue, but I suggest to add a remark in the docs that non-standard memory managers may fail with the new BIOS.

**Comment by fysnet** [comment]
Indeed, a wise suggestion. I will do so. Thank you the initial issue post. They are always welcome.
